
---
- name: Restart gpsd
  systemd:
    name: gpsd
    state: restarted

- name: Restart chrony
  systemd:
    name: chrony
    state: restarted

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Reboot if boot-config changed
  reboot:
    msg: "Rebooting to apply /boot/config.txt overlays"
    reboot_timeout: 600
